// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.26.1
// source: types/ptypes.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	DistanceAggregator_DistanceAggregator_FullMethodName = "/DistanceAggregator/DistanceAggregator"
)

// DistanceAggregatorClient is the client API for DistanceAggregator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DistanceAggregatorClient interface {
	DistanceAggregator(ctx context.Context, in *AggregateDistanceRequest, opts ...grpc.CallOption) (*None, error)
}

type distanceAggregatorClient struct {
	cc grpc.ClientConnInterface
}

func NewDistanceAggregatorClient(cc grpc.ClientConnInterface) DistanceAggregatorClient {
	return &distanceAggregatorClient{cc}
}

func (c *distanceAggregatorClient) DistanceAggregator(ctx context.Context, in *AggregateDistanceRequest, opts ...grpc.CallOption) (*None, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(None)
	err := c.cc.Invoke(ctx, DistanceAggregator_DistanceAggregator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DistanceAggregatorServer is the server API for DistanceAggregator service.
// All implementations must embed UnimplementedDistanceAggregatorServer
// for forward compatibility
type DistanceAggregatorServer interface {
	DistanceAggregator(context.Context, *AggregateDistanceRequest) (*None, error)
	mustEmbedUnimplementedDistanceAggregatorServer()
}

// UnimplementedDistanceAggregatorServer must be embedded to have forward compatible implementations.
type UnimplementedDistanceAggregatorServer struct {
}

func (UnimplementedDistanceAggregatorServer) DistanceAggregator(context.Context, *AggregateDistanceRequest) (*None, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DistanceAggregator not implemented")
}
func (UnimplementedDistanceAggregatorServer) mustEmbedUnimplementedDistanceAggregatorServer() {}

// UnsafeDistanceAggregatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DistanceAggregatorServer will
// result in compilation errors.
type UnsafeDistanceAggregatorServer interface {
	mustEmbedUnimplementedDistanceAggregatorServer()
}

func RegisterDistanceAggregatorServer(s grpc.ServiceRegistrar, srv DistanceAggregatorServer) {
	s.RegisterService(&DistanceAggregator_ServiceDesc, srv)
}

func _DistanceAggregator_DistanceAggregator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregateDistanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistanceAggregatorServer).DistanceAggregator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DistanceAggregator_DistanceAggregator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistanceAggregatorServer).DistanceAggregator(ctx, req.(*AggregateDistanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DistanceAggregator_ServiceDesc is the grpc.ServiceDesc for DistanceAggregator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DistanceAggregator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DistanceAggregator",
	HandlerType: (*DistanceAggregatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DistanceAggregator",
			Handler:    _DistanceAggregator_DistanceAggregator_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "types/ptypes.proto",
}
